.PHONY: clean All

All:
	@echo "----------Building project:[ STL_deque - Debug ]----------"
	@cd "STL_deque" && "$(MAKE)" -f  "STL_deque.mk"
clean:
	@echo "----------Cleaning project:[ STL_deque - Debug ]----------"
	@cd "STL_deque" && "$(MAKE)" -f  "STL_deque.mk" clean
